### ISSUE TITLE
Task get agent_token fails on json decode

### ISSUE THREAD

**Issue by kenjones-cisco** [CiscoCloud/microservices-infrastructure#151]
TASK: [consul | get agent_token] **********************************************
```
fatal: [cchub-dc1-01] => Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 582, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 785, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 1005, in _executor_internal_inner
    complex_args = template.template(self.basedir, complex_args, inject, fail_on_undefined=self.error_on_undefined_vars)
  File "/usr/local/lib/python2.7/dist-packages/ansible/utils/template.py", line 135, in template
    d[k] = template(basedir, v, templatevars, lookup_fatal, depth, expand_lists, convert_bare, fail_on_undefined, filter_fatal)
  File "/usr/local/lib/python2.7/dist-packages/ansible/utils/template.py", line 121, in template
    varname = template_from_string(basedir, varname, templatevars, fail_on_undefined)
  File "/usr/local/lib/python2.7/dist-packages/ansible/utils/template.py", line 368, in template_from_string
    res = jinja2.utils.concat(rf)
  File "<template>", line 9, in root
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```
Using the latest from master from commit edac27b63b31b4b37f35c03cd6fb88cb1ee34754, when I ran the site playbook it failed with the exception above. I will be doing a retry in case it was a timing issue or response from the previous task using `consul-acl-bootstrap.sh ` resulted in an invalid output.

**Comment by stevendborrelli** [comment]
Ken, can you give more details of how you are running the playbook (i.e., vagrant vs. openstack)? I want to try to replicate your issue.

**Comment by kenjones-cisco** [comment]
Openstack, specifically CCS Internal. 

I created a VM within my project to act as a starting point that is not part of the "cluster" to just create the overall cluster. Ubuntu 14.04, ansible (1.9.0.1)

**Comment by kenjones-cisco** [comment]
I added a simple debug statement to print out the response from agent_acl:

```
TASK: [consul | wait for leader] **********************************************
ok: [cchub-dc1-01]
ok: [cchub-dc1-03]
ok: [cchub-dc1-04]
ok: [cchub-dc1-02]
ok: [cchub-dc1-05]

TASK: [consul | create agent acl] *********************************************
changed: [cchub-dc1-01]

TASK: [consul | print agent_acl response] *************************************
ok: [cchub-dc1-01] => {
    "msg": "No cluster leader"
}
ok: [cchub-dc1-03] => {
    "msg": "No cluster leader"
}
ok: [cchub-dc1-04] => {
    "msg": "No cluster leader"
}
ok: [cchub-dc1-02] => {
    "msg": "No cluster leader"
}
ok: [cchub-dc1-05] => {
    "msg": "No cluster leader"
}

TASK: [consul | get agent_token] **********************************************
fatal: [cchub-dc1-01] => Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 582, in _executor
    exec_rc = self._executor_internal(host, new_stdin)
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 785, in _executor_internal
    return self._executor_internal_inner(host, self.module_name, self.module_args, inject, port, complex_args=complex_args)
  File "/usr/local/lib/python2.7/dist-packages/ansible/runner/__init__.py", line 1005, in _executor_internal_inner
    complex_args = template.template(self.basedir, complex_args, inject, fail_on_undefined=self.error_on_undefined_vars)
  File "/usr/local/lib/python2.7/dist-packages/ansible/utils/template.py", line 135, in template
    d[k] = template(basedir, v, templatevars, lookup_fatal, depth, expand_lists, convert_bare, fail_on_undefined, filter_fatal)
  File "/usr/local/lib/python2.7/dist-packages/ansible/utils/template.py", line 121, in template
    varname = template_from_string(basedir, varname, templatevars, fail_on_undefined)
  File "/usr/local/lib/python2.7/dist-packages/ansible/utils/template.py", line 368, in template_from_string
    res = jinja2.utils.concat(rf)
  File "<template>", line 9, in root
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

The response is coming back as no "No cluster leader".

**Comment by ChrisAubuchon** [comment]
Can you show the contents of /etc/consul/consul.json and `journalctl -u consul`? "No cluster leader" is a Consul issue.

**Comment by kenjones-cisco** [comment]
```
[centos@cchub-dc1-01 ~]$ sudo more /etc/consul/consul.json
{
  "datacenter": "dc1",
  "advertise_addr": "10.7.7.42",
  "node_name": "cchub-dc1-01",
  "rejoin_after_leave": true,
  "retry_join": [ "10.7.7.42", "10.7.7.40", "10.7.7.39" ],
  "server": true,
  "bootstrap_expect": 3,
  "encrypt": "DNH0CQ3BWK8IbQXyBUti5w==",
  "ca_file": "/etc/consul/ssl/ca.cert",
  "cert_file": "/etc/consul/ssl/consul.cert",
  "key_file": "/etc/consul/ssl/consul.key",
  "verify_incoming": true,
  "verify_outgoing": true,
  "data_dir": "/var/lib/consul",
  "ui_dir": "/usr/share/consul-ui",
  "disable_remote_exec": true
}
```

```
[centos@cchub-dc1-01 ~]$ sudo journalctl -u consul
-- Logs begin at Tue 2015-04-07 18:33:01 UTC, end at Tue 2015-04-07 20:21:52 UTC. --
Apr 07 18:35:53 cchub-dc1-01.novalocal systemd[1]: Starting Consul is a tool for service discovery and configuration. Consul is distributed, highly available, and extremely
Apr 07 18:35:53 cchub-dc1-01.novalocal systemd[1]: Started Consul is a tool for service discovery and configuration. Consul is distributed, highly available, and extremely
Apr 07 18:35:53 cchub-dc1-01.novalocal consul[3957]: ==> WARNING: Expect Mode enabled, expecting 3 servers
Apr 07 18:35:53 cchub-dc1-01.novalocal consul[3957]: ==> WARNING: It is highly recommended to set GOMAXPROCS higher than 1
Apr 07 18:35:53 cchub-dc1-01.novalocal consul[3957]: ==> Starting Consul agent...
Apr 07 18:35:54 cchub-dc1-01.novalocal consul[3957]: ==> Starting Consul agent RPC...
Apr 07 18:35:54 cchub-dc1-01.novalocal consul[3957]: ==> Consul agent running!
Apr 07 18:35:54 cchub-dc1-01.novalocal consul[3957]: Node name: 'cchub-dc1-01'
Apr 07 18:35:54 cchub-dc1-01.novalocal consul[3957]: Datacenter: 'dc1'
Apr 07 18:35:54 cchub-dc1-01.novalocal consul[3957]: Server: true (bootstrap: false)
Apr 07 18:35:54 cchub-dc1-01.novalocal consul[3957]: Client Addr: 127.0.0.1 (HTTP: 8500, HTTPS: -1, DNS: 8600, RPC: 8400)
Apr 07 18:35:54 cchub-dc1-01.novalocal consul[3957]: Cluster Addr: 10.7.7.42 (LAN: 8301, WAN: 8302)
Apr 07 18:35:54 cchub-dc1-01.novalocal consul[3957]: Gossip encrypt: true, RPC-TLS: true, TLS-Incoming: true
Apr 07 18:35:54 cchub-dc1-01.novalocal consul[3957]: Atlas: <disabled>
Apr 07 18:35:54 cchub-dc1-01.novalocal consul[3957]: ==> Log data will now stream in as it occurs:
Apr 07 18:35:54 cchub-dc1-01.novalocal consul[3957]: 2015/04/07 18:35:54 [INFO] serf: EventMemberJoin: cchub-dc1-01 10.7.7.42
Apr 07 18:35:54 cchub-dc1-01.novalocal consul[3957]: 2015/04/07 18:35:54 [INFO] serf: EventMemberJoin: cchub-dc1-01.dc1 10.7.7.42
Apr 07 18:35:54 cchub-dc1-01.novalocal consul[3957]: 2015/04/07 18:35:54 [INFO] raft: Node at 10.7.7.42:8300 [Follower] entering Follower state
Apr 07 18:35:54 cchub-dc1-01.novalocal consul[3957]: 2015/04/07 18:35:54 [INFO] consul: adding server cchub-dc1-01 (Addr: 10.7.7.42:8300) (DC: dc1)
Apr 07 18:35:54 cchub-dc1-01.novalocal consul[3957]: 2015/04/07 18:35:54 [INFO] consul: adding server cchub-dc1-01.dc1 (Addr: 10.7.7.42:8300) (DC: dc1)
Apr 07 18:35:54 cchub-dc1-01.novalocal consul[3957]: 2015/04/07 18:35:54 [ERR] agent: failed to sync remote state: No cluster leader
Apr 07 18:35:54 cchub-dc1-01.novalocal consul[3957]: 2015/04/07 18:35:54 [INFO] agent: Joining cluster...
Apr 07 18:35:54 cchub-dc1-01.novalocal consul[3957]: 2015/04/07 18:35:54 [INFO] agent: (LAN) joining: [10.7.7.42 10.7.7.40 10.7.7.39]
Apr 07 18:35:56 cchub-dc1-01.novalocal consul[3957]: 2015/04/07 18:35:56 [WARN] raft: EnableSingleNode disabled, and no known peers. Aborting election.
Apr 07 18:36:04 cchub-dc1-01.novalocal consul[3957]: 2015/04/07 18:36:04 [ERR] memberlist: Failed to receive remote state: EOF
Apr 07 18:36:04 cchub-dc1-01.novalocal consul[3957]: 2015/04/07 18:36:04 [ERR] http: Request /v1/acl/create?token=ac68e013-e9a7-4d52-89d9-1f28c6359ff1, error: No cluster le
Apr 07 18:36:14 cchub-dc1-01.novalocal consul[3957]: 2015/04/07 18:36:14 [INFO] agent: (LAN) joined: 1 Err: <nil>
Apr 07 18:36:14 cchub-dc1-01.novalocal consul[3957]: 2015/04/07 18:36:14 [INFO] agent: Join completed. Synced with 1 initial agents
Apr 07 18:36:22 cchub-dc1-01.novalocal consul[3957]: 2015/04/07 18:36:22 [ERR] agent: failed to sync remote state: No cluster leader
Apr 07 18:36:41 cchub-dc1-01.novalocal consul[3957]: 2015/04/07 18:36:41 [ERR] agent: failed to sync remote state: No cluster leader
Apr 07 18:37:05 cchub-dc1-01.novalocal consul[3957]: 2015/04/07 18:37:05 [ERR] agent: failed to sync remote state: No cluster leader
Apr 07 18:37:29 cchub-dc1-01.novalocal consul[3957]: 2015/04/07 18:37:29 [ERR] agent: failed to sync remote state: No cluster leader
Apr 07 18:37:44 cchub-dc1-01.novalocal consul[3957]: 2015/04/07 18:37:44 [ERR] agent: failed to sync remote state: No cluster leader
```

**Comment by ChrisAubuchon** [comment]
Are the other Consul server nodes up? It looks like this is the only one running.
```raft: EnableSingleNode disabled, and no known peers. Aborting election.```

**Comment by kenjones-cisco** [comment]
Each of the nodes have the same logs.

**Comment by ChrisAubuchon** [comment]
Are the ports open between the nodes? 8301 specifically? That's the LAN cluster port

**Comment by kenjones-cisco** [comment]
Port 8301, is not as it wasn't listed in the documentation here:
https://microservices-infrastructure.readthedocs.org/en/latest/getting_started/openstack.html#security-group

I will open that port as well and then update.

**Comment by kenjones-cisco** [comment]
Adding port 8301 did not resolve the issue by itself, but once I also added port 8300 it was able to move past the issue above.

**Comment by kenjones-cisco** [comment]
A documentation update to include ports 8300 and 8301 is the major change. Maybe a change to the consul role to check for `msg` when `ID` is not found to enable a better error message.

**Comment by kenjones-cisco** [comment]
Task Checking port 8302 being open also failed, port needed to be open.

**Comment by ChrisAubuchon** [comment]
There will be more. It looks like the OpenStack document you linked above assumes that all ports are open between your nodes.

**Comment by stevendborrelli** [comment]
@kenjones-cisco we need to update the docs, having those ports open to 0.0.0.0/0 is bad practice. The ports should only be open to the security group itself.

**Comment by kenjones-cisco** [comment]
I think this was fixed as part of #165, at least that covered my initial issue and the resolved the bad practice of using open ports for everyone.

**Comment by stevendborrelli** [comment]
@kenjones-cisco can we close this issue?

**Comment by kenjones-cisco** [comment]
Yes.
