### ISSUE TITLE
security 

### ISSUE THREAD

**Issue by nmarasoiu** [CiscoCloud/microservices-infrastructure#278]
Hi,
bash-4.3# ./security-setup 
============= Certificates =============
----> certificate authority
serial already exists
index already exists
Traceback (most recent call last):
  File "./security-setup", line 700, in <module>
    main(parser.parse_args())
  File "./security-setup", line 688, in main
    item()
  File "./security-setup", line 466, in ca
    self.openssl_subject("security-setup"), ROOT_KEY, ROOT_CERT
  File "./security-setup", line 357, in wrap_call
    status, out, err = self.call(command, **kwargs)
  File "./security-setup", line 343, in call
    proc = Popen(shlex.split(command), stdin=capture, stdout=capture, stderr=capture)
  File "/usr/lib64/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

bash-4.3# python --version
Python 2.7.8

Please advice

**Comment by ChrisAubuchon** [comment]
Is the `openssl` command in your path?

**Comment by nmarasoiu** [comment]
thanks, worked

**Comment by nmarasoiu** [comment]
Thanks, solved!
