### ISSUE TITLE
[0.2.0] KeeperErrorCode = ConnectionLoss for /mesos

### ISSUE THREAD

**Issue by nmarasoiu** [CiscoCloud/microservices-infrastructure#300]
Hi, 

With 0.2.0, I retried multiple times, both provision and destroy+up, exactly like yesterday, when it used to work.

TASK: [mesos | create zookeeper acl] ****************************************** 
failed: [default] => {"changed": true, "cmd": "docker run --rm -e ZK_AUTH=super:eLkJBbOEyKNwouGBicxn4SMv5ETT+SvD7OgjZ8c5a2Hm -e ZNODE=/mesos -e ZNODE_ACL=world:anyone:r,digest:mesos:3KXBhDZ0nQFsKCjQnlXOItGdKF4=:cdraw -e ZK_SERVER=zookeeper.service.consul:2181 --entrypoint /usr/local/bin/setacl.sh asteris/zookeeper:latest", "delta": "0:00:02.044643", "end": "2015-05-19 13:12:31.649043", "rc": 1, "start": "2015-05-19 13:12:29.604400", "warnings": []}
stderr: Exception in thread "main" org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /mesos
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:99)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
	at org.apache.zookeeper.ZooKeeper.create(ZooKeeper.java:783)
	at org.apache.zookeeper.ZooKeeperMain.processZKCmd(ZooKeeperMain.java:695)
	at org.apache.zookeeper.ZooKeeperMain.processCmd(ZooKeeperMain.java:588)
	at org.apache.zookeeper.ZooKeeperMain.executeLine(ZooKeeperMain.java:360)
	at org.apache.zookeeper.ZooKeeperMain.run(ZooKeeperMain.java:323)
	at org.apache.zookeeper.ZooKeeperMain.main(ZooKeeperMain.java:282)
stdout: Connecting to zookeeper.service.consul:2181
2015-05-19 13:12:30,509 [myid:] - INFO  [main:Environment@100] - Client environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT
2015-05-19 13:12:30,516 [myid:] - INFO  [main:Environment@100] - Client environment:host.name=885dd5140911
2015-05-19 13:12:30,517 [myid:] - INFO  [main:Environment@100] - Client environment:java.version=1.7.0_75
2015-05-19 13:12:30,522 [myid:] - INFO  [main:Environment@100] - Client environment:java.vendor=Oracle Corporation
2015-05-19 13:12:30,522 [myid:] - INFO  [main:Environment@100] - Client environment:java.home=/usr/lib/jvm/java-1.7-openjdk/jre
2015-05-19 13:12:30,522 [myid:] - INFO  [main:Environment@100] - Client environment:java.class.path=/opt/zookeeper/bin/../build/classes:/opt/zookeeper/bin/../build/lib/*.jar:/opt/zookeeper/bin/../lib/slf4j-log4j12-1.6.1.jar:/opt/zookeeper/bin/../lib/slf4j-api-1.6.1.jar:/opt/zookeeper/bin/../lib/netty-3.7.0.Final.jar:/opt/zookeeper/bin/../lib/log4j-1.2.16.jar:/opt/zookeeper/bin/../lib/jline-0.9.94.jar:/opt/zookeeper/bin/../zookeeper-3.4.6.jar:/opt/zookeeper/bin/../src/java/lib/*.jar:/opt/zookeeper/bin/../conf:
2015-05-19 13:12:30,522 [myid:] - INFO  [main:Environment@100] - Client environment:java.library.path=/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
2015-05-19 13:12:30,523 [myid:] - INFO  [main:Environment@100] - Client environment:java.io.tmpdir=/tmp
2015-05-19 13:12:30,523 [myid:] - INFO  [main:Environment@100] - Client environment:java.compiler=<NA>
2015-05-19 13:12:30,523 [myid:] - INFO  [main:Environment@100] - Client environment:os.name=Linux
2015-05-19 13:12:30,523 [myid:] - INFO  [main:Environment@100] - Client environment:os.arch=amd64
2015-05-19 13:12:30,523 [myid:] - INFO  [main:Environment@100] - Client environment:os.version=3.10.0-229.1.2.el7.x86_64
2015-05-19 13:12:30,524 [myid:] - INFO  [main:Environment@100] - Client environment:user.name=root
2015-05-19 13:12:30,524 [myid:] - INFO  [main:Environment@100] - Client environment:user.home=/root
2015-05-19 13:12:30,524 [myid:] - INFO  [main:Environment@100] - Client environment:user.dir=/opt/zookeeper
2015-05-19 13:12:30,526 [myid:] - INFO  [main:ZooKeeper@438] - Initiating client connection, connectString=zookeeper.service.consul:2181 sessionTimeout=30000 watcher=org.apache.zookeeper.ZooKeeperMain$MyWatcher@630ed791
Welcome to ZooKeeper!
2015-05-19 13:12:30,570 [myid:] - INFO  [main-SendThread(10.0.2.15:2181):ClientCnxn$SendThread@975] - Opening socket connection to server 10.0.2.15/10.0.2.15:2181. Will not attempt to authenticate using SASL (unknown error)
JLine support is enabled
2015-05-19 13:12:30,585 [myid:] - INFO  [main-SendThread(10.0.2.15:2181):ClientCnxn$SendThread@852] - Socket connection established to 10.0.2.15/10.0.2.15:2181, initiating session
2015-05-19 13:12:30,590 [myid:] - INFO  [main-SendThread(10.0.2.15:2181):ClientCnxn$SendThread@1098] - Unable to read additional data from server sessionid 0x0, likely server has closed socket, closing socket connection and attempting reconnect
[zk: zookeeper.service.consul:2181(CONNECTING) 0] addauth digest super:eLkJBbOEyKNwouGBicxn4SMv5ETT+SvD7OgjZ8c5a2Hm
[zk: zookeeper.service.consul:2181(CONNECTING) 1] 
[zk: zookeeper.service.consul:2181(CONNECTING) 1] create /mesos ""

FATAL: all hosts have already failed -- aborting

**Comment by nmarasoiu** [comment]
0.2.0
