### ISSUE TITLE
pip: ImportError: cannot import name IncompleteRead

### ISSUE THREAD

**Issue by nmarasoiu** [CiscoCloud/microservices-infrastructure#301]
nicu@nmarasoiu:~/tools/microservices-infrastructure$ sudo pip install -r requirements.txt
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.4', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 61, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 25, in <module>
    from requests.compat import IncompleteRead
ImportError: cannot import name IncompleteRead

**Comment by nmarasoiu** [comment]
python --version
Python 2.7.6

I also have python3

**Comment by nmarasoiu** [comment]
0.2.0

**Comment by stevendborrelli** [comment]
What platform are you running on? In doing a search on this, it is a python pip problem: https://bugs.launchpad.net/ubuntu/+source/python-pip/+bug/1306991

**Comment by nmarasoiu** [comment]
solved with easy_install -U pip
