### ISSUE TITLE
Need for a stable branch/tag

### ISSUE THREAD

**Issue by nmarasoiu** [CiscoCloud/microservices-infrastructure#314]
Hi,

As mentioned in my reports, on both master and 0.2.0 I get the error below.
There is an issue just for that.
This issue is to target a stable tag/branch, because currently, I have nothing to start.
3 days ago, I was able to start it, but since than I could not longer do it.

failed: [default] => {"changed": true, "cmd": "docker run --rm -e ZK_AUTH=super:+Nt5e/wmF5gt4tN04SB/syZnqam10nNjoTHL1m+d4bt5 -e ZNODE=/mesos -e ZNODE_ACL=world:anyone:r,digest:mesos:J+OaGBhZLLsFv0iG/Dpj4HWXTyI=:cdraw -e ZK_SERVER=zookeeper.service.consul:2181 --entrypoint /usr/local/bin/setacl.sh asteris/zookeeper:latest", "delta": "0:00:02.203213", "end": "2015-05-20 12:55:39.430565", "rc": 1, "start": "2015-05-20 12:55:37.227352", "warnings": []}
stderr: Exception in thread "main" org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /mesos
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:99)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
	at org.apache.zookeeper.ZooKeeper.create(ZooKeeper.java:783)
	at org.apache.zookeeper.ZooKeeperMain.processZKCmd(ZooKeeperMain.java:695)
	at org.apache.zookeeper.ZooKeeperMain.processCmd(ZooKeeperMain.java:588)
	at org.apache.zookeeper.ZooKeeperMain.executeLine(ZooKeeperMain.java:360)
	at org.apache.zookeeper.ZooKeeperMain.run(ZooKeeperMain.java:323)
	at org.apache.zookeeper.ZooKeeperMain.main(ZooKeeperMain.java:282)
stdout: Connecting to zookeeper.service.consul:2181
2015-05-20 12:55:38,220 [myid:] - INFO  [main:Environment@100] - Client environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT
2015-05-20 12:55:38,226 [myid:] - INFO  [main:Environment@100] - Client environment:host.name=6d36177c1ccf
2015-05-20 12:55:38,226 [myid:] - INFO  [main:Environment@100] - Client environment:java.version=1.7.0_75
2015-05-20 12:55:38,234 [myid:] - INFO  [main:Environment@100] - Client environment:java.vendor=Oracle Corporation
2015-05-20 12:55:38,234 [myid:] - INFO  [main:Environment@100] - Client environment:java.home=/usr/lib/jvm/java-1.7-openjdk/jre
2015-05-20 12:55:38,234 [myid:] - INFO  [main:Environment@100] - Client environment:java.class.path=/opt/zookeeper/bin/../build/classes:/opt/zookeeper/bin/../build/lib/*.jar:/opt/zookeeper/bin/../lib/slf4j-log4j12-1.6.1.jar:/opt/zookeeper/bin/../lib/slf4j-api-1.6.1.jar:/opt/zookeeper/bin/../lib/netty-3.7.0.Final.jar:/opt/zookeeper/bin/../lib/log4j-1.2.16.jar:/opt/zookeeper/bin/../lib/jline-0.9.94.jar:/opt/zookeeper/bin/../zookeeper-3.4.6.jar:/opt/zookeeper/bin/../src/java/lib/*.jar:/opt/zookeeper/bin/../conf:
2015-05-20 12:55:38,235 [myid:] - INFO  [main:Environment@100] - Client environment:java.library.path=/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
2015-05-20 12:55:38,235 [myid:] - INFO  [main:Environment@100] - Client environment:java.io.tmpdir=/tmp
2015-05-20 12:55:38,235 [myid:] - INFO  [main:Environment@100] - Client environment:java.compiler=<NA>
2015-05-20 12:55:38,235 [myid:] - INFO  [main:Environment@100] - Client environment:os.name=Linux
2015-05-20 12:55:38,235 [myid:] - INFO  [main:Environment@100] - Client environment:os.arch=amd64
2015-05-20 12:55:38,235 [myid:] - INFO  [main:Environment@100] - Client environment:os.version=3.10.0-229.1.2.el7.x86_64
2015-05-20 12:55:38,235 [myid:] - INFO  [main:Environment@100] - Client environment:user.name=root
2015-05-20 12:55:38,235 [myid:] - INFO  [main:Environment@100] - Client environment:user.home=/root
2015-05-20 12:55:38,236 [myid:] - INFO  [main:Environment@100] - Client environment:user.dir=/opt/zookeeper
2015-05-20 12:55:38,237 [myid:] - INFO  [main:ZooKeeper@438] - Initiating client connection, connectString=zookeeper.service.consul:2181 sessionTimeout=30000 watcher=org.apache.zookeeper.ZooKeeperMain$MyWatcher@636aa365

**Comment by ChrisAubuchon** [comment]
Try pulling the fix/gh-254 branch and running `vagrant up`. It removes external dependencies when starting a vagrant instance

**Comment by nmarasoiu** [comment]
Running fix/gh-254 raises the issue:
https://github.com/CiscoCloud/microservices-infrastructure/issues/279
