### ISSUE TITLE
[ansible/zookeeper] ConnectionLoss for /mesos

### ISSUE THREAD

**Issue by nmarasoiu** [CiscoCloud/microservices-infrastructure#423]
Hi,

First time  I run ansible (after fresh terraform provisioning in aws), it works.
Second time (third and so on), it gives the error below.
It was an extremely frequent error with local vagrant deploys too.
Right now I keep ramping new clusters every time.
What is happening? Is there a solution?
Thanks
Nicu Marasoiu

TASK: [mesos | create zookeeper acl] ****************************************** 
failed: [mi-control-01] => {"changed": true, "cmd": ["docker", "run", "--rm", "-e", "ZK_AUTH=super:+Nt5e/wmF5gt4tN04SB/syZnqam10nNjoTHL1m+d4bt5", "-e", "ZNODE=/mesos", "-e", "ZNODE_ACL=world:anyone:r,digest:mesos:J+OaGBhZLLsFv0iG/Dpj4HWXTyI=:cdraw", "-e", "ZK_SERVER=zookeeper.service.consul:2181", "--entrypoint", "/usr/local/bin/setacl.sh", "ciscocloud/zookeeper:0.2"], "delta": "0:00:02.475471", "end": "2015-06-02 12:08:04.286288", "rc": 1, "start": "2015-06-02 12:08:01.810817", "warnings": []}
stderr: Exception in thread "main" org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /mesos
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:99)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
	at org.apache.zookeeper.ZooKeeper.create(ZooKeeper.java:783)
	at org.apache.zookeeper.ZooKeeperMain.processZKCmd(ZooKeeperMain.java:695)
	at org.apache.zookeeper.ZooKeeperMain.processCmd(ZooKeeperMain.java:588)
	at org.apache.zookeeper.ZooKeeperMain.executeLine(ZooKeeperMain.java:360)
	at org.apache.zookeeper.ZooKeeperMain.run(ZooKeeperMain.java:323)
	at org.apache.zookeeper.ZooKeeperMain.main(ZooKeeperMain.java:282)
stdout: Connecting to zookeeper.service.consul:2181
2015-06-02 12:08:03,244 [myid:] - INFO  [main:Environment@100] - Client environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT
2015-06-02 12:08:03,251 [myid:] - INFO  [main:Environment@100] - Client environment:host.name=8d3f5b8e34d6
2015-06-02 12:08:03,251 [myid:] - INFO  [main:Environment@100] - Client environment:java.version=1.7.0_75
2015-06-02 12:08:03,256 [myid:] - INFO  [main:Environment@100] - Client environment:java.vendor=Oracle Corporation
2015-06-02 12:08:03,256 [myid:] - INFO  [main:Environment@100] - Client environment:java.home=/usr/lib/jvm/java-1.7-openjdk/jre
2015-06-02 12:08:03,256 [myid:] - INFO  [main:Environment@100] - Client environment:java.class.path=/opt/zookeeper/bin/../build/classes:/opt/zookeeper/bin/../build/lib/*.jar:/opt/zookeeper/bin/../lib/slf4j-log4j12-1.6.1.jar:/opt/zookeeper/bin/../lib/slf4j-api-1.6.1.jar:/opt/zookeeper/bin/../lib/netty-3.7.0.Final.jar:/opt/zookeeper/bin/../lib/log4j-1.2.16.jar:/opt/zookeeper/bin/../lib/jline-0.9.94.jar:/opt/zookeeper/bin/../zookeeper-3.4.6.jar:/opt/zookeeper/bin/../src/java/lib/*.jar:/opt/zookeeper/bin/../conf:
2015-06-02 12:08:03,256 [myid:] - INFO  [main:Environment@100] - Client environment:java.library.path=/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
2015-06-02 12:08:03,257 [myid:] - INFO  [main:Environment@100] - Client environment:java.io.tmpdir=/tmp
2015-06-02 12:08:03,257 [myid:] - INFO  [main:Environment@100] - Client environment:java.compiler=<NA>
2015-06-02 12:08:03,257 [myid:] - INFO  [main:Environment@100] - Client environment:os.name=Linux
2015-06-02 12:08:03,257 [myid:] - INFO  [main:Environment@100] - Client environment:os.arch=amd64
2015-06-02 12:08:03,257 [myid:] - INFO  [main:Environment@100] - Client environment:os.version=3.10.0-123.8.1.el7.x86_64
2015-06-02 12:08:03,257 [myid:] - INFO  [main:Environment@100] - Client environment:user.name=root
2015-06-02 12:08:03,257 [myid:] - INFO  [main:Environment@100] - Client environment:user.home=/root
2015-06-02 12:08:03,257 [myid:] - INFO  [main:Environment@100] - Client environment:user.dir=/opt/zookeeper
2015-06-02 12:08:03,258 [myid:] - INFO  [main:ZooKeeper@438] - Initiating client connection, connectString=zookeeper.service.consul:2181 sessionTimeout=30000 watcher=org.apache.zookeeper.ZooKeeperMain$MyWatcher@4af45223
Welcome to ZooKeeper!
JLine support is enabled
2015-06-02 12:08:03,312 [myid:] - INFO  [main-SendThread(mi-control-02:2181):ClientCnxn$SendThread@975] - Opening socket connection to server mi-control-02/10.0.164.170:2181. Will not attempt to authenticate using SASL (unknown error)
2015-06-02 12:08:03,343 [myid:] - WARN  [main-SendThread(mi-control-02:2181):ClientCnxn$SendThread@1102] - Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
[zk: zookeeper.service.consul:2181(CONNECTING) 0] addauth digest super:+Nt5e/wmF5gt4tN04SB/syZnqam10nNjoTHL1m+d4bt5
[zk: zookeeper.service.consul:2181(CONNECTING) 1] 
[zk: zookeeper.service.consul:2181(CONNECTING) 1] create /mesos ""
2015-06-02 12:08:03,457 [myid:] - INFO  [main-SendThread(mi-control-01:2181):ClientCnxn$SendThread@975] - Opening socket connection to server mi-control-01/10.0.119.65:2181. Will not attempt to authenticate using SASL (unknown error)
2015-06-02 12:08:03,458 [myid:] - WARN  [main-SendThread(mi-control-01:2181):ClientCnxn$SendThread@1102] - Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)

FATAL: all hosts have already failed -- aborting

**Comment by nmarasoiu** [comment]
Reproduces consistently on second, third ansible application with terraform.yml,
my latest master commit I am is:
commit eca1776df6e4a55128c6cc0c5bfb7368b54c3cdf
Author: Brian Hicks <brian@brianthicks.com>
Date:   Mon Jun 1 09:38:29 2015 -0500

    roles: add bootstrap tag to all network dependencies

**Comment by nmarasoiu** [comment]
so, scenario:
1. rm terraform.tfstate*; terraform get; terraform plan; terraform apply
ansible-playbook -i plugins/inventory/terraform.py -e @security.yml terraform.yml
Result: OK, all up, I can deploy stuff on the cluster and works.
2. 
ansible-playbook -i plugins/inventory/terraform.py -e @security.yml terraform.yml
Result: error zookeeper above

**Comment by stevendborrelli** [comment]
Thanks for the bug report. We'll try to duplicate this issue and see what is going on.

**Comment by stevendborrelli** [comment]
@nmarasoiu are you still seeing this issue with 0.3.0?

**Comment by nmarasoiu** [comment]
(no, luks ok, run twice)
