### ISSUE TITLE
Odd connection error

### ISSUE THREAD

**Issue by PeterLamar** [CiscoCloud/microservices-infrastructure#79]
I get a weird connection error now, let me know if anything jumps out and I'll keep looking at it. 

user@user-VirtualBox:~/Documents/microservices-infrastructure$ ansible-playbook openstack/destroy-hosts.yml 

PLAY [localhost] ************************************************************** 

TASK: [verify openstack environment] ****************************************** 
skipping: [localhost] => (item=OS_USERNAME)
skipping: [localhost] => (item=OS_PASSWORD)

PLAY [all] ******************************************************************** 

TASK: [nova_compute ] ********************************************************* 
failed: [host-02] => {"failed": true, "parsed": false}
Traceback (most recent call last):
  File "/home/user/.ansible/tmp/ansible-tmp-1425844436.47-13529309033022/nova_compute", line 2294, in <module>
    main()
  File "/home/user/.ansible/tmp/ansible-tmp-1425844436.47-13529309033022/nova_compute", line 573, in main
    nova.authenticate()
  File "/usr/local/lib/python2.7/dist-packages/novaclient/client.py", line 169, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/novaclient/v1_1/client.py", line 239, in authenticate
    self.client.authenticate()
  File "/usr/local/lib/python2.7/dist-packages/novaclient/client.py", line 586, in authenticate
    auth_url = self._v2_auth(auth_url)
  File "/usr/local/lib/python2.7/dist-packages/novaclient/client.py", line 677, in _v2_auth
    return self._authenticate(url, body)
  File "/usr/local/lib/python2.7/dist-packages/novaclient/client.py", line 690, in _authenticate
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/novaclient/client.py", line 439, in _time_request
    resp, body = self.request(url, method, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/novaclient/client.py", line 410, in request
    **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 378, in send
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='us-texas-1.cisco.com', port=5000): Max retries exceeded with url: /v2.0/tokens (Caused by <class 'socket.gaierror'>: [Errno -2] Name or service not known)

All I have updated is db1 in group vars:

user@user-VirtualBox:~/Documents/microservices-infrastructure/inventory/group_vars$ cat dc1

os_auth_url: https://us-texas-1.cisco.com:5000/v2.0
os_tenant_name: petlamar-test
os_tenant_id: 66eb7caf5999435a81647b09499*****
os_net_id: e7b1be4f-e0d2-4024-948f-b9e6c491****
consul_dc: dc1

**Comment by keithchambers** [comment]
Do you have ```python-novaclient``` and ```python-keystoneclient``` installed?

Which version are you running of each?

I've had issues with stability when running the latest versions.  These older versions are known to work:
```
python-keystoneclient (1.1.0)
python-novaclient (2.17.0)
```

**Comment by PeterLamar** [comment]
Created a fresh image of trusty and reinstalled, works fine now. It likely was the versions but perhaps something else. I am working through all the NooB issues at least :)
