### ISSUE TITLE
master fail | sysctl max file limit

### ISSUE THREAD

**Issue by tymofii-polekhin** [CiscoCloud/microservices-infrastructure#814]
Cloned master today and tried to deploy.
Got:
```
TASK: [common | sysctl max file limit] ****************************************
failed: [mi-worker-002] => {"failed": true, "parsed": false}
/etc/profile.d/lang.sh: line 19: warning: setlocale: LC_CTYPE: cannot change locale (UTF-8): No such file or directory
BECOME-SUCCESS-wfzyckbrbwbuzllibrtsmdrwhpvsuzja
/bin/sh: warning: setlocale: LC_CTYPE: cannot change locale (UTF-8): No such file or directory
Traceback (most recent call last):
  File "/home/centos/.ansible/tmp/ansible-tmp-1447668228.64-62933258846373/sysctl", line 1936, in <module>
    main()
  File "/home/centos/.ansible/tmp/ansible-tmp-1447668228.64-62933258846373/sysctl", line 335, in main
    result = SysctlModule(module)
  File "/home/centos/.ansible/tmp/ansible-tmp-1447668228.64-62933258846373/sysctl", line 118, in __init__
    self.process()
  File "/home/centos/.ansible/tmp/ansible-tmp-1447668228.64-62933258846373/sysctl", line 157, in process
    elif not self._values_is_equal(self.proc_value, self.args['value']):
  File "/home/centos/.ansible/tmp/ansible-tmp-1447668228.64-62933258846373/sysctl", line 178, in _values_is_equal
    b = b.split()
AttributeError: 'int' object has no attribute 'split'
```

**Comment by sehqlr** [comment]
@tymofii-polekhin What version of Ansible are you running? The most recent version allows for ints, but I want to make this backwards compatible, and I want to test against the version that you have.

**Comment by sehqlr** [comment]
When ciscocloud/consul-rpm#1 gets accepted, this configuration will be added in the package itself, so that is the long-term solution to this problem.

**Comment by BrianHicks** [comment]
that PR is merged. Is there a PR or WIP branch removing that Ansible task?

**Comment by sehqlr** [comment]
I'm putting a fresh one together now

**Comment by tymofii-polekhin** [comment]
@sehqlr this is what i got:
```
➜  ansible  uname -a
Darwin TPOLIEKH-M-H1RB 15.0.0 Darwin Kernel Version 15.0.0: Sat Sep 19 15:53:46 PDT 2015; root:xnu-3247.10.11~1/RELEASE_X86_64 x86_64
➜  ansible  ansible --version
ansible 1.9.0.1
  configured module search path = None
```

**Comment by sehqlr** [comment]
Thanks, @tymofii-polekhin. Until #806 is addressed, I'll remember to double check for all of our supported versions, and I'll try to get that into some automated testing, as well.
